# Generated by Django 2.1.4 on 2019-01-17 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballHalfSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballHalfSeasonLeagueTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveSmallIntegerField()),
                ('won', models.PositiveSmallIntegerField()),
                ('lost', models.PositiveSmallIntegerField()),
                ('GF', models.PositiveSmallIntegerField()),
                ('GA', models.PositiveSmallIntegerField()),
                ('GD', models.SmallIntegerField()),
                ('points', models.PositiveSmallIntegerField()),
                ('half_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballHalfSeason')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('team1_two_points', models.PositiveSmallIntegerField()),
                ('team2_two_points', models.PositiveSmallIntegerField()),
                ('team1_three_points', models.PositiveSmallIntegerField()),
                ('team2_three_points', models.PositiveSmallIntegerField()),
                ('team1_faults', models.PositiveSmallIntegerField()),
                ('team2_faults', models.PositiveSmallIntegerField()),
                ('team1_penalty_faults', models.PositiveSmallIntegerField()),
                ('team2_penalty_faults', models.PositiveSmallIntegerField()),
                ('team1_last_score', models.PositiveSmallIntegerField()),
                ('team2_last_score', models.PositiveSmallIntegerField()),
                ('team1_first_quarter_score', models.PositiveSmallIntegerField()),
                ('team2_first_quarter_score', models.PositiveSmallIntegerField()),
                ('team1_second_quarter_score', models.PositiveSmallIntegerField()),
                ('team2_second_quarter_score', models.PositiveSmallIntegerField()),
                ('team1_third_quarter_score', models.PositiveSmallIntegerField()),
                ('team2_third_quarter_score', models.PositiveSmallIntegerField()),
                ('team1_fourth_quarter_score', models.PositiveSmallIntegerField()),
                ('team2_fourth_quarter_score', models.PositiveSmallIntegerField()),
                ('team1_rebounds', models.PositiveSmallIntegerField()),
                ('team2_rebounds', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketballMatchPlayersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_substitute', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballMatch')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballPenaltyFailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballMatch')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballPenaltyFault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballMatch')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('birth_date', models.DateTimeField()),
                ('position', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballSubstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
                ('in_out', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballMatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballPlayer')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballTeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballHalfSeason')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballPlayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballTeam')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballThreePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballMatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballPlayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballTeam')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballTwoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballMatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballPlayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('time', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FootballAssist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FootballCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FootballGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FootballHalfSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FootballHalfSeasonLeagueTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveSmallIntegerField()),
                ('won', models.PositiveSmallIntegerField()),
                ('drawn', models.PositiveSmallIntegerField()),
                ('lost', models.PositiveSmallIntegerField()),
                ('GF', models.PositiveSmallIntegerField()),
                ('GA', models.PositiveSmallIntegerField()),
                ('GD', models.SmallIntegerField()),
                ('points', models.PositiveSmallIntegerField()),
                ('half_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballHalfSeason')),
            ],
        ),
        migrations.CreateModel(
            name='FootballLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FootballMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('team1_corners', models.PositiveSmallIntegerField()),
                ('team2_corners', models.PositiveSmallIntegerField()),
                ('team1_faults', models.PositiveSmallIntegerField()),
                ('team2_faults', models.PositiveSmallIntegerField()),
                ('team1_goals', models.PositiveSmallIntegerField()),
                ('team2_goals', models.PositiveSmallIntegerField()),
                ('team1_goal_positions', models.PositiveSmallIntegerField()),
                ('team2_goal_positions', models.PositiveSmallIntegerField()),
                ('team1_assists', models.PositiveSmallIntegerField()),
                ('team2_assists', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballMatchPlayersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_substitute', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballMatch')),
            ],
        ),
        migrations.CreateModel(
            name='FootballPenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballMatch')),
            ],
        ),
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('birth_date', models.DateTimeField()),
                ('position', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FootballSubstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
                ('in_out', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballMatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballPlayer')),
            ],
        ),
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FootballTeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballHalfSeason')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballPlayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballTeam')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body_text', models.TextField()),
                ('date', models.DateField()),
                ('basketball_league', models.ManyToManyField(to='Sport3.BasketballLeague')),
                ('basketball_match', models.ManyToManyField(to='Sport3.BasketballMatch')),
                ('basketball_player', models.ManyToManyField(to='Sport3.BasketballPlayer')),
                ('basketball_team', models.ManyToManyField(to='Sport3.BasketballTeam')),
                ('football_league', models.ManyToManyField(to='Sport3.FootballLeague')),
                ('football_match', models.ManyToManyField(to='Sport3.FootballMatch')),
                ('football_player', models.ManyToManyField(to='Sport3.FootballPlayer')),
                ('football_team', models.ManyToManyField(to='Sport3.FootballTeam')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='sources',
            field=models.ManyToManyField(to='Sport3.NewsSources'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='Sport3.NewsTags'),
        ),
        migrations.AddField(
            model_name='footballpenalty',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='footballpenalty',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballmatchplayerslist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='footballmatchplayerslist',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='best_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='half_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballHalfSeason'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballLeague'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballhalfseasonleagueteams',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballLeague'),
        ),
        migrations.AddField(
            model_name='footballhalfseasonleagueteams',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballhalfseason',
            name='league',
            field=models.ManyToManyField(to='Sport3.FootballLeague'),
        ),
        migrations.AddField(
            model_name='footballgoal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballMatch'),
        ),
        migrations.AddField(
            model_name='footballgoal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='footballgoal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballcard',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballMatch'),
        ),
        migrations.AddField(
            model_name='footballcard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='footballcard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballassist',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballMatch'),
        ),
        migrations.AddField(
            model_name='footballassist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='footballassist',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballTeam'),
        ),
        migrations.AddField(
            model_name='basketballpenaltyfault',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballPlayer'),
        ),
        migrations.AddField(
            model_name='basketballpenaltyfault',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballTeam'),
        ),
        migrations.AddField(
            model_name='basketballpenaltyfailed',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballPlayer'),
        ),
        migrations.AddField(
            model_name='basketballpenaltyfailed',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballTeam'),
        ),
        migrations.AddField(
            model_name='basketballmatchplayerslist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballPlayer'),
        ),
        migrations.AddField(
            model_name='basketballmatchplayerslist',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballTeam'),
        ),
        migrations.AddField(
            model_name='basketballmatch',
            name='best_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='basketballmatch',
            name='half_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballHalfSeason'),
        ),
        migrations.AddField(
            model_name='basketballmatch',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballLeague'),
        ),
        migrations.AddField(
            model_name='basketballmatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.FootballTeam'),
        ),
        migrations.AddField(
            model_name='basketballhalfseasonleagueteams',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballLeague'),
        ),
        migrations.AddField(
            model_name='basketballhalfseasonleagueteams',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sport3.BasketballTeam'),
        ),
        migrations.AddField(
            model_name='basketballhalfseason',
            name='league',
            field=models.ManyToManyField(to='Sport3.BasketballLeague'),
        ),
    ]
